version: "3"
services:
  app:
    container_name: "pytorch_container"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: pytorch_container
    volumes:
        - $PWD:/home/workspase
    tty: true
